var modalC="";
modalC += "                                  <div id=\"modal-"+ml_num+"\" class=\"uk-modal\">";
modalC += "                                        <div class=\"uk-modal-dialog uk-modal-dialog-lightbox\">";
modalC += "                                            <a href=\"#\" class=\"uk-modal-close uk-close uk-close-alt\"><\/a>";
modalC += "                                               <div class=\"uk-grid\" >";
modalC += "                                                 <div class=\"uk-width-medium-1-1\">";
modalC += "                                                   <figure class=\"uk-overlay\">";
modalC += "                                                     <img width=\"600\" height=\"400\" src=\""+ipath+"\" alt=\"\">";
modalC += "                                                         <figcaption class=\"uk-overlay-panel uk-overlay-bottom uk-overlay-background\">";
modalC += "                                                         <div class=\"uk-grid\">";
modalC += "                                                            <div class=\"uk-width-1-2 uk-text-left uk-text-small\">";
modalC += "                                                            "+rltr+"";
modalC += "                                                            <\/div>";
modalC += "                                                            <div class=\"uk-width-1-2 uk-text-right\">";
modalC += dom+" days listed<\/span>\";
modalC += "                                                            <\/div>";
modalC += "                                                          <\/div>";
modalC += "                                                          <\/figcaption>";
modalC += "                                                  <\/figure>";
modalC += "                                                 <\/div>";
modalC += "                                               <\/div>";
modalC += "                                               <div class=\"uk-grid\" style=\"margin-top: 2px; margin-bottom: 4px;\">";
modalC += "                                                <div class=\"uk-width-1-2 uk-text-left\" >";
modalC += "                                                  <ul class=\"uk-list\">";
modalC += "                                                    <li><span  style=\"margin-left: 5px;\">"+asking+"<\/span><\/li>";
modalC += "                                                    <li><span  style=\"margin-left: 5px;\">"+bed+" beds \/ "+bath+" baths\"?><\/span><\/li>";
modalC += "                                                    <li><\/li>";
modalC += "                                                  <\/ul>";
modalC += "                                                 <\/div>";
modalC += "                                                 <div class=\"uk-width-1-2 uk-text-right\" >";
modalC += "                                                  <ul class=\"uk-list\">";
modalC += "                                                   <li><span  style=\"margin-right: 5px;\">"+addr+"<\/span><\/li>";
modalC += "                                                   <li><span   style=\"margin-right: 5px; \">"+community+"<\/span><\/li>";
modalC += "                                                  <\/ul>";
modalC += "                                                <\/div>";
modalC += "                                                 <div class=\"uk-width-1-1  uk-container-center uk-text-center\" style=\"margin-top: 2px; margin-bottom: 4px;\">";
modalC += "";
modalC += "                                                 <a class=\"uk-button uk-button-primary\" href=\""+ipath+"\">View Full Listing&nbsp;<i class=\"uk-icon-justify uk-icon-hand-o-right\"><\/i>&nbsp;<\/a>";
modalC += "                                                 <\/div>";
modalC += "                                               <\/div>";
modalC += "                                        <\/div>";
