DROP TABLE IF EXISTS IMG_QUEUE;
CREATE TABLE `IMG_QUEUE` (
`id` int(64) unsigned NOT NULL AUTO_INCREMENT,
`img` varchar(120) NOT NULL DEFAULT '',
`action` varchar(1) NOT NULL DEFAULT 'C',
`dt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8
  
